<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>
    <NBGV_DoNotEmitNonVersionCustomAttributes>true</NBGV_DoNotEmitNonVersionCustomAttributes>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>MSBuild.StructuredLogger.Utils</PackageId>
    <Authors>Kirill Osenkov, Microsoft</Authors>
    <Company>Microsoft</Company>
    <Description>Utility helpers for analyzing and processing MSBuild structured log (.binlog) files. Builds on top of MSBuild.StructuredLogger.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/KirillOsenkov/MSBuildStructuredLog</PackageProjectUrl>
    <IconFilePath>$(MSBuildThisFileDirectory)..\StructuredLogViewer\icons\msbuild-structured-log-viewer.png</IconFilePath>
    <PackageIcon>msbuild-structured-log-viewer.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/KirillOsenkov/MSBuildStructuredLog</RepositoryUrl>
    <PackageTags>MSBuild Log Logger Structure Structured</PackageTags>
  </PropertyGroup>
  <ItemGroup Condition=" '$(OS)' == 'Windows_NT' ">
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
  </ItemGroup>
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);NETCORE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
    <PackageReference Include="DotUtils.MsBuild.BinlogRedactor.SensitiveDataDetector" />
    <PackageReference Include="NuGet.ProjectModel" />
    <PackageReference Include="GuiLabs.Language.Xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\StructuredLogger\StructuredLogger.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="$(IconFilePath)" Pack="true" PackagePath="" />
    <None Include="$(MSBuildThisFileDirectory)..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <PropertyGroup Condition=" '$(OS)' == 'Windows_NT' ">
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\StructuredLogger\key.snk</AssemblyOriginatorKeyFile>
    <DelaySign>False</DelaySign>
  </PropertyGroup>
</Project>
